name=Arduino_SpiDrvNINA
version=0.0.1
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Spi driver for NINA modules
paragraph=With this library you can send and receive messages through the SPI interface.
category=Communication
url=http://www.arduino.cc/en/Reference/Arduino_SpiDrvNINA
architectures=samd,mbed_rp2040,megaavr
includes=Arduino_SpiDrvNINA.h
